# Generated by Django 4.2.25 on 2026-03-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
    ]
