# Generated by Django 4.2.25 on 2026-03-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
    ]
